language: python
python:
  - "2.7"
  - "3.4"
before_script:
  - psql template1 -c 'create extension hstore;'
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
script:
  - flake8 .
  - py.test --ds=gopherairtime.testsettings */tests.py
